### ISSUE TITLE
[Feat] 학생 정보 API

### ISSUE THREAD

**Issue by BaekJaehyuk** [ITA-OneByte/OneByte-BE#10]
## 📝 기능 개요

회원과 관련된  전반적인 API 기능을 구현합니다.

## ✅ Todo
- [x] 학생 정보 등록
- [x] 학생 정보 삭제
- [x] 학생 목록 조회
- [x] 학생 정보 수정
- [x] 학생 세부 정보 조회
