### ISSUE TITLE
[Feat] 비밀번호 수정 API

### ISSUE THREAD

**Issue by BaekJaehyuk** [ITA-OneByte/OneByte-BE#104]
## 📝 기능 개요

사용자의 이메일의 인증을 통한 사용자 확인을 거쳐, 비밀번호 변경

## ✅ Todo
- [x] 이메일 인증 코드로 사용자 확인
- [x] 비밀번호 수정
- [x] 이메일 인증 토큰 관련 레디스 키 네이밍 수정
- [x] 이메일 검증 용도 ENUM 추가
