### ISSUE TITLE
[Feat] 엔티티 관계 및 필드 설정

### ISSUE THREAD

**Issue by BaekJaehyuk** [ITA-OneByte/OneByte-BE#11]
## 📝 기능 개요
패키지 구조 및 엔티티 관계 설정

## ✅ Todo
- [x] User 도메인 생성
- [x] MainClass 도메인 생성
- [x] SubClass 도메인 생성
- [x] ClassStudent 도메인 생성
- [x] Student 도메인 생성
- [x] Attendance 도메인 생성
