### ISSUE TITLE
[Feat] 일정 관리

### ISSUE THREAD

**Issue by dpfls0922** [ITA-OneByte/OneByte-BE#113]
## 📝 기능 개요
일정 관리 관련 API입니다.

## ✅ Todo
- [x] 캘린더 카테고리 CRUD
- [x] 일정등록
- [x] 월별 일정 조회
- [x] 모달 등록(스케줄/할 일)/조회/수정/삭제

### 📚 Remarks
- 색상 String 말고 Enum으로 관리하도록 수정하기
- 기획 완료된 후 반복 필드 수정하기
- 기획 완료된 후 이벤트 타입 필드 추가하는 로직으로 수정하기
- 일정 등록 시 참석자 필드 추가하기
