### ISSUE TITLE
[Feat] 클래스 API

### ISSUE THREAD

**Issue by dpfls0922** [ITA-OneByte/OneByte-BE#13]
## 📝 기능 개요
메인 카테고리와 서브 카테고리의 관계 정보를 보여주는 API 입니다.

## ✅ Todo
- [ ] 클래스 정보 API
- [ ] 메인 클래스 crud
- [ ] 서브 클래스 crud
