### ISSUE TITLE
[Feat] 성적관리 API

### ISSUE THREAD

**Issue by bangyewon** [ITA-OneByte/OneByte-BE#94]
## 📝 기능 개요
성적 관리 관한 api 제작

## ✅ Todo
- [x] 시험지 조회 api
- [x] 시험지 상세내용 조회 api
- [x] 시험지 수정 api
- [x] 시험지 삭제 api
- [x] 개인 성적 수정 api

### 📚 Remarks
시헙지 조회시 다른 member 시험지까지 모두 조회
